# Generated by Django 3.0.8 on 2020-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sub_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
