# Generated by Django 3.0.8 on 2020-08-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200801_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='subject',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='sub_subject',
            new_name='sub_category',
        ),
    ]
